NEMS driver cleanup (#98)
* cice6 compile (#71) (#34)

* update cice6 component mk

* update path for forapps/ufs

* update paths to MOM6 and CICE interfaces (#33)

Co-authored-by: Rahul Mahajan <aerorahul@users.noreply.github.com>

Co-authored-by: Rahul Mahajan <aerorahul@users.noreply.github.com>

* start cleanup

* remove NEMS mediator files and Spaceweather Mediator file

* remove FieldDictionary add and unused components

* use fd_nems.yaml for FieldDictionary
* remove unused FRONT_COMPONENT and DriverAddComp:
* NMMB,GSM,MOM5,CICE5,POM,WRFHYDRO
* "S" components, "X" components

* remove ESMF Version<8 code blocks

* clean up error logging

*use  ChkErr function like in CMEPS,MOM6,CICE6 caps

* clean up DriverAddComp statements

* reduce lines required to add each component or reporting
on an unfound component by adding "found_comp" logical. This
allows a single error statement to be used for each possible
"not found" error

* add attribute print flag

* add logical flag to control whether attributes are written to
PET logs at startup

* set attribute printing false

* remove unused bits of NEMS_UTILS; whitespace cleanup

* remove RTC and TIMEF from MAIN_NEMS

* remove earth and nems internal state files

* replace ifdef IBM to fix gnu compile failure

/scratch2/NCEPDEV/nwprod/hpc-stack/src/hpc-stack/pkg/upp-upp_v10.0.6/sorc/ncep_post.fd/PROCESS.f:81: undefined reference to `timef_'

Co-authored-by: Rahul Mahajan <aerorahul@users.noreply.github.com>